logging:
  level:
    root: INFO
    io.kafbat.ui: DEBUG
    reactor.netty.http.server.AccessLog: INFO
    org.springframework.security: DEBUG

server:
 port: 8080

kafka:
  clusters:
    - name: local
      bootstrapServers: localhost:9092

dynamic.config.enabled: true

