name: charmed-kafka-ui # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '1.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Kafka UI snap # 79 char long summary
description: |
  snap for the kafka kafbat ui
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

system-usernames:
  _daemon_: shared

hooks:
  install: 
    plugs: 
      - network
      - network-bind
      - mount-observe

environment:
  JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64

apps:
  daemon:
    command: opt/kafka-ui/bin/start-wrapper.bash
    daemon: simple
    install-mode: disable
    plugs: 
      - network
      - network-bind
      - mount-observe

parts:
  kafka-ui:
    plugin: nil
    source: https://github.com/kafbat/kafka-ui.git
    build-packages:
    - openjdk-21-jdk
    override-build: |
      ./gradlew clean build -Pinclude-frontend=true -Pversion=${SNAPCRAFT_PROJECT_VERSION} -x test && cp -r ./* $CRAFT_PART_INSTALL
    stage: 
    - api
    override-prime: |
      mkdir -p $CRAFT_PRIME/opt/kafka-ui/libs
      mkdir -p $CRAFT_PRIME/opt/kafka-ui/config

      cp $CRAFT_STAGE/api/build/libs/* $CRAFT_PRIME/opt/kafka-ui/libs
      cp $CRAFT_STAGE/api/src/main/resources/application-local.yml $CRAFT_PRIME/opt/kafka-ui/config
  base:
    plugin: nil
    stage-packages:
    - openjdk-21-jdk
    - util-linux
  wrapper:
    plugin: dump
    source: snap/local
