name: charmed-kafka-ui
base: core24
version: '1.2.0'
summary: Charmed Kafka UI for Charmed Operators
description: |
  This is a snap that provides `kafbat/kafka-ui`, intended for use in the Charmed Kafka UI Charmed Operator.
grade: stable
confinement: strict

platforms:
  amd64:

system-usernames:
  _daemon_: shared

hooks:
  install: 
    plugs: 
      - network
      - network-bind
      - mount-observe

environment:
  JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64

apps:
  daemon:
    command: opt/kafka-ui/bin/start-wrapper.bash
    daemon: simple
    install-mode: disable
    plugs: 
      - network
      - network-bind
      - mount-observe
  keytool:
    command: usr/lib/jvm/java-21-openjdk-amd64/bin/keytool
    plugs:
      - mount-observe

parts:
  kafka-ui:
    plugin: nil
    source: https://github.com/kafbat/kafka-ui.git
    build-packages:
    - openjdk-21-jdk
    override-pull: |
      craftctl default
      # patching upstream bug
      sed -i '/if (entry.name().contains("inter.broker.protocol.version")) {/,/}/d' api/src/main/java/io/kafbat/ui/service/ReactiveAdminClient.java
    override-build: |
      ./gradlew clean build -Pinclude-frontend=true -Pversion=${SNAPCRAFT_PROJECT_VERSION} -x test && cp -r ./* $CRAFT_PART_INSTALL
    stage: 
    - api
    override-prime: |
      mkdir -p $CRAFT_PRIME/opt/kafka-ui/libs
      mkdir -p $CRAFT_PRIME/opt/kafka-ui/config

      cp $CRAFT_STAGE/api/build/libs/* $CRAFT_PRIME/opt/kafka-ui/libs
  base:
    plugin: nil
    stage-packages:
    - openjdk-21-jdk
    - util-linux
  wrapper:
    plugin: dump
    source: snap/local
