#!/usr/bin/env bash

set -eux

export COMPONENT='kafka-ui'

export CONF="${SNAP_DATA}"/etc/$COMPONENT
export LOGS="${SNAP_COMMON}"/var/log/$COMPONENT

mkdir -p $CONF
mkdir -p $LOGS

chmod -R 770 "${LOGS}"
chown -R 584792:root "${LOGS}"

# copying default config from squashfs
cp "${SNAP}"/opt/$COMPONENT/config/* $CONF
